spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/dorm?authSource=admin&useUnicode=yes&characterEncoding=UTF-8
generator:
  minDate: 2016-09-01
  maxDate: 2026-07-15
  student:
    male-names:
      - Александр
      - Алексей
      - Борис
      - Виктор
      - Владимир
      - Григорий
      - Дмитрий
      - Денис
      - Евгений
      - Игорь
      - Константин
      - Кирилл
      - Никита
      - Леонид
      - Роман
      - Сергей
      - Максим
      - Тимофей
      - Иван
      - Яков
      - Петр
      - Олег
      - Николай
      - Михаил
      - Матвей
      - Лев
      - Артур
      - Геннадий
      - Георгий
      - Аркадий
      - Артем
      - Вадим
      - Богдан
      - Руслан
    male-surenames:
      - Смирнов
      - Иванов
      - Кузнецов
      - Соколов
      - Попов
      - Лебедев
      - Козлов
      - Новиков
      - Морозов
      - Петров
      - Волков
      - Соловьёв
      - Васильев
      - Зайцев
      - Павлов
      - Семёнов
      - Голубев
      - Виноградов
      - Богданов
      - Воробьёв
      - Фёдоров
      - Михайлов
      - Беляев
      - Тарасов
      - Белов
      - Комаров
      - Орлов
      - Киселёв
      - Макаров
      - Андреев
    female-names:
      - Александра
      - Алена
      - Анна
      - Анастасия
      - Валерия
      - Вера
      - Виктория
      - Вероника
      - Дарья
      - Евгения
      - Екатерина
      - Елизавета
      - Инна
      - Ирина
      - Кира
      - Кристина
      - Ксения
      - Лариса
      - Лидия
      - Любовь
      - Майя
      - Маргарита
      - Марина
      - Мария
      - Недежда
      - Олеся
      - Ольга
      - София
      - Татьяна
      - Ульяна
    female-surenames:
      - Смирнова
      - Иванова
      - Кузнецова
      - Соколова
      - Попова
      - Лебедева
      - Козлова
      - Новикова
      - Морозова
      - Петрова
      - Волкова
      - Соловьёва
      - Васильева
      - Зайцева
      - Павлова
      - Семёнова
      - Голубева
      - Виноградова
      - Богданова
      - Воробьёва
      - Фёдорова
      - Михайлова
      - Беляева
      - Тарасова
      - Белова
      - Комарова
      - Орлова
      - Киселёва
      - Макарова
      - Андреева
    male-middlenames:
        - Александрович
        - Алексеевич
        - Анатольевич
        - Андреевич
        - Антонович
        - Васильевич
        - Викторович
        - Витальевич
        - Владимирович
        - Всеволодович
        - Иванович
        - Игоревич
        - Борисович
        - Семенович
        - Сергеевич
        - Станиславович
        - Евгеньевич
        - Егорович
        - Макарович
        - Максимович
        - Маркович
        - Матвеевич
        - Леонидович
        - Львович
        - Павлович
        - Петрович
        - Гаврилович
        - Геннадиевич
        - Георгиевич
        - Олегов
    female-middlenames:
        - Александровна
        - Алексеевна
        - Анатольевна
        - Андреевна
        - Антоновна
        - Васильевна
        - Викторовна
        - Витальевна
        - Владимировна
        - Всеволодовна
        - Ивановна
        - Игоревна
        - Борисовна
        - Семеновна
        - Сергеевна
        - Станиславовна
        - Евгеньевна
        - Егоровна
        - Макаровна
        - Максимовна
        - Марковна
        - Матвеевна
        - Леонидовна
        - Львовна
        - Павловна
        - Петровна
        - Гавриловна
        - Геннадиевна
        - Георгиевна
        - Олеговна
  dormitory:
    minRoomNumber: 500
    maxRoomNumber: 1000
    locations:
      - Студенческий городок, пер. Вяземский, д. 5/7
      - Общежитие №2, ул. Ленсовета, д. 23, лит. А
      - Общежитие № 3,  Альпийский пер., д.15, к. 2, лит. А
      - Общежитие № 4, ул. Белорусская, д. 6, лит. А
      - Межвузовский студенческий городок, пр. Новоизмайловский, д. 16
      - Доходный дом, наб. р. Карповки, д. 22, к. 2, лит. Б
  room:
    minRoomCapacity: 2
    maxRoomCapacity: 4
    maxWarningNumber: 5
---
spring:
  profiles:
    prod:
  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb:27017/dorm?authSource=admin&useUnicode=yes&characterEncoding=UTF-8