version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  dorm-service:
    image: blackjackj/dorm-server:latest
    container_name: dorm-server
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: default,prod
    links:
      - mongodb
    depends_on:
      - mongodb
